const companies = [
    {
    "uid": "C0001135",
    "id": 1135,
    "auction_id": 2,
    "name": "Tune Protect Sdn Bhd",
    "merimen_name": "Tune Protect",
    "display_name": null,
    "type": "STORAGE",
    "sell_only": 0,
    "gov_id": "0262925M",
    "other_id_1": null,
    "other_id_2": null,
    "other_id_3": null,
    "phone": "07-7730633",
    "fax": null,
    "url": null,
    "address1": "No 1, Jalan Teknologi 6",
    "address2": "Kawasan Perindustrian Mengkibol",
    "city": "Kluang",
    "state": "JHR",
    "post_code": "86000",
    "country": "MYS",
    "industry": null,
    "consign_type": "CORP",
    "ar_terms": "COD",
    "ap_terms": "07D",
    "payment_reconciliation": "CONSIGNOR",
    "net_off": 0,
    "hirer_pays_charge": 0,
    "gst_num": null,
    "gst_expiry": null,
    "gst_verify_date": null,
    "bank_name": null,
    "bank_route_num": null,
    "bank_acct_num": null,
    "notes": null,
    "status": "ACTIVE",
    "status_at": null,
    "status_by": null,
    "status_note": null,
    "created_by": "Desmond Chin",
    "updated_by": "Desmond Chin",
    "created_at": "2020-06-17T07:50:40.000Z",
    "updated_at": "2020-06-17T07:50:40.000Z",
    "active": 1,
    "contact_details": "PIC : Ms Winnie (0127711173)",
    "comp_email": "uniquecl_auto@yahoo.com",
    "storage_fee_markup": 10,
    "towing_fee_markup": 10,
    "pre_storage_rate": 10,
    "pre_storage_maxcap": 1000,
    "storage_note": null,
    "towing_note": null,
    "payment_method": "CASH",
    "storage_type": "Other",
    "d365_cust_id": "CUST000004631",
    "d365_vendor_id": "SUPP000003230",
    "created_by_role": "FINANCE",
    "updated_by_role": "FINANCE",
    "number_of_users": 0,
    "name_linked": "companies/1135",
    "name_linked_target": "_self"
    },
    {
    "uid": "C0001134",
    "id": 1134,
    "auction_id": 2,
    "name": "Tune Protect HQ Sdn Bhd",
    "merimen_name": "Tune Protect HQ",
    "display_name": "Private",
    "type": "DEALER",
    "sell_only": 0,
    "gov_id": "590218105597",
    "other_id_1": null,
    "other_id_2": null,
    "other_id_3": null,
    "phone": "0192413133",
    "fax": null,
    "url": null,
    "address1": "xxx\n",
    "address2": "xxx",
    "city": "Petaling Jaya",
    "state": "SGR",
    "post_code": "41200",
    "country": "MYS",
    "industry": "AUTO",
    "consign_type": "PRIV",
    "ar_terms": "COD",
    "ap_terms": "07D",
    "payment_reconciliation": "AUCTION",
    "net_off": 0,
    "hirer_pays_charge": 0,
    "gst_num": null,
    "gst_expiry": null,
    "gst_verify_date": null,
    "bank_name": "BPUBLIC",
    "bank_route_num": null,
    "bank_acct_num": "3173479023",
    "notes": null,
    "status": "ACTIVE",
    "status_at": null,
    "status_by": null,
    "status_note": null,
    "created_by": "Lim Siao Chee",
    "updated_by": "Lim Siao Chee",
    "created_at": "2020-06-17T03:45:43.000Z",
    "updated_at": "2020-06-17T03:45:58.000Z",
    "active": 1,
    "contact_details": null,
    "comp_email": "thiamhoemotor@outlook.com",
    "storage_fee_markup": 10,
    "towing_fee_markup": 10,
    "pre_storage_rate": 0,
    "pre_storage_maxcap": 1000,
    "storage_note": null,
    "towing_note": null,
    "payment_method": null,
    "storage_type": null,
    "d365_cust_id": "CUST000004623",
    "d365_vendor_id": "SUPP000003229",
    "created_by_role": "FINANCE",
    "updated_by_role": "FINANCE",
    "number_of_users": 0,
    "name_linked": "companies/1134",
    "name_linked_target": "_self"
    },
    // {
    // "uid": "C0001133",
    // "id": 1133,
    // "auction_id": 2,
    // "name": "Choo Tong Meng",
    // "display_name": "Private",
    // "type": "DEALER",
    // "sell_only": 0,
    // "gov_id": "671128085013",
    // "other_id_1": null,
    // "other_id_2": null,
    // "other_id_3": null,
    // "phone": "0162898981",
    // "fax": null,
    // "url": null,
    // "address1": "No. 19, Jalan PP 3/9",
    // "address2": "Putra Perdana",
    // "city": "Puchong ",
    // "state": "SGR",
    // "post_code": "47130",
    // "country": "MYS",
    // "industry": "AUTO",
    // "consign_type": "PRIV",
    // "ar_terms": "COD",
    // "ap_terms": "07D",
    // "payment_reconciliation": "AUCTION",
    // "net_off": 0,
    // "hirer_pays_charge": 0,
    // "gst_num": null,
    // "gst_expiry": null,
    // "gst_verify_date": null,
    // "bank_name": "BMALAY",
    // "bank_route_num": null,
    // "bank_acct_num": "162889005624",
    // "notes": null,
    // "status": "ACTIVE",
    // "status_at": null,
    // "status_by": null,
    // "status_note": null,
    // "created_by": "Lim Siao Chee",
    // "updated_by": "Lim Siao Chee",
    // "created_at": "2020-06-17T03:37:53.000Z",
    // "updated_at": "2020-06-17T03:38:38.000Z",
    // "active": 1,
    // "contact_details": null,
    // "comp_email": "elaine_sen@hotmail.com",
    // "storage_fee_markup": 10,
    // "towing_fee_markup": 10,
    // "pre_storage_rate": 0,
    // "pre_storage_maxcap": 1000,
    // "storage_note": null,
    // "towing_note": null,
    // "payment_method": null,
    // "storage_type": null,
    // "d365_cust_id": null,
    // "d365_vendor_id": null,
    // "created_by_role": "FINANCE",
    // "updated_by_role": "FINANCE",
    // "number_of_users": 0,
    // "name_linked": "companies/1133",
    // "name_linked_target": "_self"
    // },
    // {
    // "uid": "C0001132",
    // "id": 1132,
    // "auction_id": 2,
    // "name": "KUALA FREIGHT MOVERS SDN BHD",
    // "display_name": null,
    // "type": "STORAGE",
    // "sell_only": 0,
    // "gov_id": "0035635A",
    // "other_id_1": null,
    // "other_id_2": null,
    // "other_id_3": null,
    // "phone": "012-2196023",
    // "fax": null,
    // "url": null,
    // "address1": "Lot 8, Jalan Sultan Mohamed 6,",
    // "address2": "Kawasan Perusahan",
    // "city": "Klang",
    // "state": "SGR",
    // "post_code": "42000",
    // "country": "MYS",
    // "industry": "AUTO",
    // "consign_type": "CORP",
    // "ar_terms": "COD",
    // "ap_terms": "07D",
    // "payment_reconciliation": "CONSIGNOR",
    // "net_off": 0,
    // "hirer_pays_charge": 0,
    // "gst_num": null,
    // "gst_expiry": null,
    // "gst_verify_date": null,
    // "bank_name": "BCIMB",
    // "bank_route_num": null,
    // "bank_acct_num": "8002121740",
    // "notes": null,
    // "status": "ACTIVE",
    // "status_at": null,
    // "status_by": null,
    // "status_note": null,
    // "created_by": "Desmond Chin",
    // "updated_by": "Desmond Chin",
    // "created_at": "2020-06-16T08:06:24.000Z",
    // "updated_at": "2020-06-16T08:06:24.000Z",
    // "active": 1,
    // "contact_details": "Person in charge : Ms Amerin (012-2196023)",
    // "comp_email": "accounts@kfm.my",
    // "storage_fee_markup": 10,
    // "towing_fee_markup": 10,
    // "pre_storage_rate": 10,
    // "pre_storage_maxcap": 1000,
    // "storage_note": null,
    // "towing_note": null,
    // "payment_method": "EFT",
    // "storage_type": "Other",
    // "d365_cust_id": "CUST000004596",
    // "d365_vendor_id": "SUPP000003208",
    // "created_by_role": "FINANCE",
    // "updated_by_role": "FINANCE",
    // "number_of_users": 0,
    // "name_linked": "companies/1132",
    // "name_linked_target": "_self"
    // },
    // {
    // "uid": "C0001131",
    // "id": 1131,
    // "auction_id": 2,
    // "name": "MPV Car Service Sdn Bhd",
    // "display_name": null,
    // "type": "STORAGE",
    // "sell_only": 0,
    // "gov_id": "0724190M",
    // "other_id_1": null,
    // "other_id_2": null,
    // "other_id_3": null,
    // "phone": "03-62805555",
    // "fax": null,
    // "url": null,
    // "address1": "No 22 Jalan Tago 11,",
    // "address2": "Kawasan Perindustrian Tago Sri Damansara, ",
    // "city": "Kuala Lumpur",
    // "state": "KUL",
    // "post_code": "52200",
    // "country": "MYS",
    // "industry": null,
    // "consign_type": "CORP",
    // "ar_terms": "COD",
    // "ap_terms": "07D",
    // "payment_reconciliation": "CONSIGNOR",
    // "net_off": 0,
    // "hirer_pays_charge": 0,
    // "gst_num": null,
    // "gst_expiry": null,
    // "gst_verify_date": null,
    // "bank_name": "BMALAY",
    // "bank_route_num": null,
    // "bank_acct_num": "562553508409",
    // "notes": null,
    // "status": "ACTIVE",
    // "status_at": null,
    // "status_by": null,
    // "status_note": null,
    // "created_by": "Desmond Chin",
    // "updated_by": "Desmond Chin",
    // "created_at": "2020-06-15T08:18:46.000Z",
    // "updated_at": "2020-06-15T08:18:46.000Z",
    // "active": 1,
    // "contact_details": "PIC : Mr Leong (0122168488)",
    // "comp_email": "kia_mpvbody@yahoo.com",
    // "storage_fee_markup": 10,
    // "towing_fee_markup": 10,
    // "pre_storage_rate": 10,
    // "pre_storage_maxcap": 1000,
    // "storage_note": null,
    // "towing_note": null,
    // "payment_method": "EFT",
    // "storage_type": "Other",
    // "d365_cust_id": "CUST000004559",
    // "d365_vendor_id": "SUPP000003161",
    // "created_by_role": "FINANCE",
    // "updated_by_role": "FINANCE",
    // "number_of_users": 0,
    // "name_linked": "companies/1131",
    // "name_linked_target": "_self"
    // },
    // {
    // "uid": "C0001130",
    // "id": 1130,
    // "auction_id": 2,
    // "name": "Tan Chong Ekspres Auto Servis Sdn Bhd (KUANTAN)",
    // "display_name": null,
    // "type": "STORAGE",
    // "sell_only": 0,
    // "gov_id": "88888",
    // "other_id_1": null,
    // "other_id_2": null,
    // "other_id_3": null,
    // "phone": "09-5363160",
    // "fax": null,
    // "url": null,
    // "address1": "Lot 1/3486, Jalan Gambang, ",
    // "address2": "Batu 3 1/2,  Kampung Sungai Isap,",
    // "city": "Kuantan",
    // "state": "PHG",
    // "post_code": "25150",
    // "country": "MYS",
    // "industry": "AUTO",
    // "consign_type": "CORP",
    // "ar_terms": "COD",
    // "ap_terms": "07D",
    // "payment_reconciliation": "CONSIGNOR",
    // "net_off": 0,
    // "hirer_pays_charge": 0,
    // "gst_num": null,
    // "gst_expiry": null,
    // "gst_verify_date": null,
    // "bank_name": "BCIMB",
    // "bank_route_num": null,
    // "bank_acct_num": "98268499922268",
    // "notes": null,
    // "status": "ACTIVE",
    // "status_at": null,
    // "status_by": null,
    // "status_note": null,
    // "created_by": "Desmond Chin",
    // "updated_by": "Desmond Chin",
    // "created_at": "2020-06-15T06:23:30.000Z",
    // "updated_at": "2020-06-17T09:51:00.000Z",
    // "active": 1,
    // "contact_details": "PIC : Ms Sin (0169616268)\nMs Siew (019-3327583)",
    // "comp_email": "puikee.sin@tanchonggroup.com",
    // "storage_fee_markup": 10,
    // "towing_fee_markup": 10,
    // "pre_storage_rate": 10,
    // "pre_storage_maxcap": 1000,
    // "storage_note": null,
    // "towing_note": null,
    // "payment_method": "EFT",
    // "storage_type": "Panel",
    // "d365_cust_id": "CUST000004552",
    // "d365_vendor_id": "SUPP000003144",
    // "created_by_role": "FINANCE",
    // "updated_by_role": "FINANCE",
    // "number_of_users": 0,
    // "name_linked": "companies/1130",
    // "name_linked_target": "_self"
    // },
    // {
    // "uid": "C0001129",
    // "id": 1129,
    // "auction_id": 2,
    // "name": "Kok Khong Wai",
    // "display_name": "Private",
    // "type": "DEALER",
    // "sell_only": 0,
    // "gov_id": "750129-08-5803",
    // "other_id_1": null,
    // "other_id_2": null,
    // "other_id_3": null,
    // "phone": "012-2123623",
    // "fax": null,
    // "url": null,
    // "address1": "No. 33, Jalan KP 2/2, Kota Perdana, ",
    // "address2": "Bandar Putra Permai ",
    // "city": "Seri Kembangan",
    // "state": "SGR",
    // "post_code": "43300",
    // "country": "MYS",
    // "industry": "AUTO",
    // "consign_type": "FLEET",
    // "ar_terms": "COD",
    // "ap_terms": "07D",
    // "payment_reconciliation": "AUCTION",
    // "net_off": 0,
    // "hirer_pays_charge": 0,
    // "gst_num": null,
    // "gst_expiry": null,
    // "gst_verify_date": null,
    // "bank_name": "BMALAY",
    // "bank_route_num": null,
    // "bank_acct_num": "1142-3604-7850",
    // "notes": null,
    // "status": "ACTIVE",
    // "status_at": null,
    // "status_by": null,
    // "status_note": null,
    // "created_by": "Desmond Chin",
    // "updated_by": "Desmond Chin",
    // "created_at": "2020-06-15T02:36:37.000Z",
    // "updated_at": "2020-06-15T02:36:37.000Z",
    // "active": 1,
    // "contact_details": null,
    // "comp_email": "rooverccsc@hotmail.com",
    // "storage_fee_markup": 10,
    // "towing_fee_markup": 10,
    // "pre_storage_rate": 0,
    // "pre_storage_maxcap": 1000,
    // "storage_note": null,
    // "towing_note": null,
    // "payment_method": null,
    // "storage_type": null,
    // "d365_cust_id": "CUST000004556",
    // "d365_vendor_id": "SUPP000003147",
    // "created_by_role": "FINANCE",
    // "updated_by_role": "FINANCE",
    // "number_of_users": 0,
    // "name_linked": "companies/1129",
    // "name_linked_target": "_self"
    // },
    // {
    // "uid": "C0001128",
    // "id": 1128,
    // "auction_id": 2,
    // "name": "Au Kok Seng",
    // "display_name": "Private",
    // "type": "DEALER",
    // "sell_only": 0,
    // "gov_id": "610406-05-5457",
    // "other_id_1": null,
    // "other_id_2": null,
    // "other_id_3": null,
    // "phone": "012-3125288",
    // "fax": null,
    // "url": null,
    // "address1": "No. 30, Jalan Pinggiran Putra,",
    // "address2": "50A Le Putra Avenue",
    // "city": "Seri Kembangan",
    // "state": "SGR",
    // "post_code": "43300",
    // "country": "MYS",
    // "industry": "AUTO",
    // "consign_type": "FLEET",
    // "ar_terms": "COD",
    // "ap_terms": "07D",
    // "payment_reconciliation": "AUCTION",
    // "net_off": 0,
    // "hirer_pays_charge": 0,
    // "gst_num": null,
    // "gst_expiry": null,
    // "gst_verify_date": null,
    // "bank_name": "BPUBLIC",
    // "bank_route_num": null,
    // "bank_acct_num": "6-351411834",
    // "notes": null,
    // "status": "ACTIVE",
    // "status_at": null,
    // "status_by": null,
    // "status_note": null,
    // "created_by": "Desmond Chin",
    // "updated_by": "Desmond Chin",
    // "created_at": "2020-06-15T02:34:34.000Z",
    // "updated_at": "2020-06-15T02:34:42.000Z",
    // "active": 1,
    // "contact_details": null,
    // "comp_email": "vicky4504@hotmail.com",
    // "storage_fee_markup": 10,
    // "towing_fee_markup": 10,
    // "pre_storage_rate": 0,
    // "pre_storage_maxcap": 1000,
    // "storage_note": null,
    // "towing_note": null,
    // "payment_method": null,
    // "storage_type": null,
    // "d365_cust_id": "CUST000004557",
    // "d365_vendor_id": "SUPP000003148",
    // "created_by_role": "FINANCE",
    // "updated_by_role": "FINANCE",
    // "number_of_users": 0,
    // "name_linked": "companies/1128",
    // "name_linked_target": "_self"
    // },
    // {
    // "uid": "C0001127",
    // "id": 1127,
    // "auction_id": 2,
    // "name": "Jaya Hoong Motor Services Sdn. Bhd.",
    // "display_name": null,
    // "type": "STORAGE",
    // "sell_only": 0,
    // "gov_id": "0685287D",
    // "other_id_1": null,
    // "other_id_2": null,
    // "other_id_3": null,
    // "phone": "07-3514229",
    // "fax": null,
    // "url": null,
    // "address1": "No.4 Jalan Rosmerah 1/3, ",
    // "address2": "Taman Johor Jaya,",
    // "city": "Johor Bahru",
    // "state": "JHR",
    // "post_code": "81100",
    // "country": "MYS",
    // "industry": null,
    // "consign_type": "CORP",
    // "ar_terms": "COD",
    // "ap_terms": "07D",
    // "payment_reconciliation": "CONSIGNOR",
    // "net_off": 0,
    // "hirer_pays_charge": 0,
    // "gst_num": null,
    // "gst_expiry": null,
    // "gst_verify_date": null,
    // "bank_name": "BPUBLIC",
    // "bank_route_num": null,
    // "bank_acct_num": "3107861504",
    // "notes": null,
    // "status": "ACTIVE",
    // "status_at": null,
    // "status_by": null,
    // "status_note": null,
    // "created_by": "Desmond Chin",
    // "updated_by": "Desmond Chin",
    // "created_at": "2020-06-12T04:18:43.000Z",
    // "updated_at": "2020-06-12T04:19:33.000Z",
    // "active": 1,
    // "contact_details": "PIC : Mr Hau (0167694112)",
    // "comp_email": "hoongmotor@gmail.com",
    // "storage_fee_markup": 10,
    // "towing_fee_markup": 10,
    // "pre_storage_rate": 10,
    // "pre_storage_maxcap": 1000,
    // "storage_note": null,
    // "towing_note": null,
    // "payment_method": "EFT",
    // "storage_type": "Other",
    // "d365_cust_id": "CUST000004511",
    // "d365_vendor_id": "SUPP000003136",
    // "created_by_role": "FINANCE",
    // "updated_by_role": "FINANCE",
    // "number_of_users": 0,
    // "name_linked": "companies/1127",
    // "name_linked_target": "_self"
    // },
    // {
    // "uid": "C0001126",
    // "id": 1126,
    // "auction_id": 2,
    // "name": "Christine Dawn Fletcher",
    // "display_name": "Private ",
    // "type": "DEALER",
    // "sell_only": 0,
    // "gov_id": "761227125630",
    // "other_id_1": null,
    // "other_id_2": null,
    // "other_id_3": null,
    // "phone": "0126680869",
    // "fax": null,
    // "url": null,
    // "address1": "A1203A Perdana Condo ",
    // "address2": "Jalan PJU 8/1, Badar Damansara Perdana ",
    // "city": "Petaling Jaya",
    // "state": "SGR",
    // "post_code": "47820",
    // "country": "MYS",
    // "industry": "AUTO",
    // "consign_type": "PRIV",
    // "ar_terms": "COD",
    // "ap_terms": "07D",
    // "payment_reconciliation": "AUCTION",
    // "net_off": 0,
    // "hirer_pays_charge": 0,
    // "gst_num": null,
    // "gst_expiry": null,
    // "gst_verify_date": null,
    // "bank_name": "BCIMB",
    // "bank_route_num": null,
    // "bank_acct_num": "7012712720",
    // "notes": null,
    // "status": "ACTIVE",
    // "status_at": null,
    // "status_by": null,
    // "status_note": null,
    // "created_by": "Lim Siao Chee",
    // "updated_by": "Lim Siao Chee",
    // "created_at": "2020-06-12T03:53:11.000Z",
    // "updated_at": "2020-06-12T03:53:11.000Z",
    // "active": 1,
    // "contact_details": null,
    // "comp_email": "shazlansaphian@gmail.com",
    // "storage_fee_markup": 10,
    // "towing_fee_markup": 10,
    // "pre_storage_rate": 0,
    // "pre_storage_maxcap": 1000,
    // "storage_note": null,
    // "towing_note": null,
    // "payment_method": null,
    // "storage_type": null,
    // "d365_cust_id": "CUST000004521",
    // "d365_vendor_id": "SUPP000003138",
    // "created_by_role": "FINANCE",
    // "updated_by_role": "FINANCE",
    // "number_of_users": 0,
    // "name_linked": "companies/1126",
    // "name_linked_target": "_self"
    // }
    ];

// const companiesMeta =  companies.map(company => ({ id: company.id, name: company.name, merimen_name: company.merimen_name }) )
// // console.log(companiesMeta)

// const dd =  companiesMeta.filter(company => "Tune Protect HQ".includes(company.merimen_name));
// // const dd =  companiesMeta.filter(company => company.merimen_name == "Tune Protect KL");
// console.log(dd);

// console.log(['TMB', 'TMB1', 'TMB2' ,"TM"].filter(name => "TMB2".includes(name)));

const consignors = {
    "AIG Malaysia Insurance Berhad": 1,
    "AXA Affin General Insurance Berhad": 6,
    "Liberty Insurance Berhad": 39,
    "Tokio Marine Insurans (Malaysia) Berhad": 10,
    "Zurich General Takaful Malaysia Berhad": 49,
    "Zurich General Insurance Malaysia Berhad": 48,
    "Takaful Ikhlas General Berhad": 756,
    "MSIG INSURANCE (MALAYSIA) BHD": 40,
    "TUNE PROTECT MALAYSIA": 879,
    "Allianz General Insurance Company (Malaysia) Berhad": 919,
    "QBE Insurance (Malaysia) Berhad": 38,
    "Lonpac Insurance": 965,
    "Great Eastern General Insurance": 979,
    "Chubb Insurance Malaysia Berhad": 1062
};

const ddd = Object.keys(consignors).filter(consignor => consignor.includes("Allianz"));
console.log(ddd);
console.log('DDDD', consignors[ddd[0]]);